-- 公司主表
CREATE TABLE [dbo].[Company](
	[CompanyId] [nvarchar](10) NOT NULL,
	[CompanyName] [nvarchar](100) NOT NULL,
	[IndustryId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CompanyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- 產業表
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Industry](
	[IndustryId] [int] IDENTITY(1,1) NOT NULL,
	[IndustryName] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IndustryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[IndustryName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
-- 資料表與索引
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MonthlyRevenue](
	[ReportDate] [nvarchar](10) NOT NULL,
	[DataYearMonth] [nvarchar](6) NOT NULL,
	[CompanyId] [nvarchar](10) NOT NULL,
	[Revenue] [decimal](18, 2) NOT NULL,
	[LastMonthRevenue] [decimal](18, 2) NULL,
	[LastYearMonthRevenue] [decimal](18, 2) NULL,
	[MoMChange] [decimal](18, 15) NULL,
	[YoYChange] [decimal](18, 15) NULL,
	[AccRevenue] [decimal](18, 2) NULL,
	[LastYearAccRevenue] [decimal](18, 2) NULL,
	[AccChange] [decimal](18, 15) NULL,
	[Memo] [nvarchar](200) NULL,
 CONSTRAINT [PK_MonthlyRevenue] PRIMARY KEY CLUSTERED 
(
	[CompanyId] ASC,
	[DataYearMonth] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [IDX_CompanyId] ON [dbo].[MonthlyRevenue]
(
	[CompanyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO

CREATE NONCLUSTERED INDEX [IDX_DataYearMonth] ON [dbo].[MonthlyRevenue]
(
	[DataYearMonth] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Company]  WITH CHECK ADD FOREIGN KEY([IndustryId])
REFERENCES [dbo].[Industry] ([IndustryId])
GO
ALTER TABLE [dbo].[MonthlyRevenue]  WITH CHECK ADD FOREIGN KEY([CompanyId])
REFERENCES [dbo].[Company] ([CompanyId])
GO

-- 查詢 SP
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GetMonthlyRevenueByCompanyId]
	@CompanyId NVARCHAR(10) = NULL,
	@OutString NVARCHAR(8) OUTPUT
AS
BEGIN
	BEGIN TRY
		SELECT * FROM MonthlyRevenue
		WHERE @CompanyId IS NULL OR CompanyId = @CompanyId
		SET @OutString = '00000000';
	END TRY
	BEGIN CATCH
		SET @OutString = '99999999';
	END CATCH
END
